version: '3.7'
x-app-args: &app-args
  ARCHITECTURE: ${ARCHITECTURE}
  ORTOOLS_URL: ${ORTOOLS_URL}
  ORTOOLS_VERSION: ${ORTOOLS_VERSION}
  RUBY_VERSION: ${RUBY_VERSION}

x-app: &default-app
  volumes:
    - ./:/srv/app/
  env_file:
    - ./.env

services:
  main:
    <<: *default-app
    build:
      args:
        <<: *app-args
      context: .
      dockerfile: Dockerfile
    image: dev.example.com/mapotempo/optimizer-ortools
    tty: true
